### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by gitzaai** [justoverclockl/og-meta-tag#1]
Flarum0.1.0-beta.15
PHP7.4.21
MySQL10.4.19-MariaDB

composer require justoverclock/og-meta-tag:"*"
./composer.json has been updated
Running composer update justoverclock/og-meta-tag
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires justoverclock/og-meta-tag * -> satisfiable by justoverclock/og-meta-tag[0.1.0].
    - justoverclock/og-meta-tag 0.1.0 requires flarum/core ^1.0 -> found flarum/core[v1.0.0, ..., v1.0.4] but it conflicts with your root composer.json require (^0.1.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by justoverclockl** [comment]
you have Flarum beta 15, this extension is compatible only for 1.0.*
